language: clojure
lein: lein2
install: (cd cloverage && lein2 deps) && (cd lein-cloverage && lein2 deps)
script: (cd cloverage && lein2 test) && (cd lein-cloverage && lein2 test)
sudo: false
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

after_success:
  - bash deploy.sh
